### ISSUE TITLE
Readme instructions are wrong - hash doesn't exist

### ISSUE THREAD

**Issue by berney** [maltzj/google-style-precommit-hook#26]
The readme includes instructions:

```yaml
repos:
- repo: https://github.com/maltzj/google-style-precommit-hook
  sha: b7e9e7fcba4a5aea463e72fe9964c14877bd8130
    hooks:
      - id: google-style-java
```

There is no hash `b7e9e7fcba4a5aea463e72fe9964c14877bd8130` in this projects git history.

```
git fetch --all
git log --all | grep -i b7e9e7fcba4a5aea463e72fe9964c14877bd8130 --count
0
```

Also since pre-commit 1.7.0, it should be `rev` not `sha`.

It would be convenient to use tags for releases IMO, but SHAs have the benefit of being immutable. If they were correct.
